services:
  arob2:
    image: aroblab2
    build:
      context: ./docker/
      dockerfile: Dockerfile
    container_name: aroblab2
    environment:
      DISPLAY: $DISPLAY
      ROS_LOCALHOST_ONLY: 1
    privileged: true
    volumes:
      # X11
      - ~/.Xauthority:/root/.Xauthority
      # 
      - /dev/:/dev
      # Code
      - ./pXX_arob_lab2_drones:/root/catkin_ws/src/pXX_arob_lab2_drones
    network_mode: "host"
    command: tail -f /dev/null
